alter table SEC_USER_ROLE add SECURITY_SCOPE varchar2(255)^

drop index IDX_SEC_USER_ROLE_UNIQ_ROLE^
create unique index IDX_SEC_USER_ROLE_UNIQ_ROLE on SEC_USER_ROLE(USER_ID, ROLE_ID, SECURITY_SCOPE, DELETE_TS)^

